### ISSUE TITLE
Adding styles to the plugin

### ISSUE THREAD

**Issue by mokhosh** [CodeWithDennis/filament-simple-alert#10]
Are you open to merging a PR that adds the required styles to the plugin so users don't need to add custom styles?

Related: https://github.com/CodeWithDennis/filament-simple-alert/issues/7

**Comment by CodeWithDennis** [comment]
Isn't that already in the README?

> Make sure you add the following to your `tailwind.config.js file.
> 
> './vendor/codewithdennis/filament-simple-alert/resources/**/*.blade.php',

**Comment by mokhosh** [comment]
No, I mean add the css to the plugin itself, so the user doesn't have to build it himself.

**Comment by CodeWithDennis** [comment]
I don't think that's necessary. Plus, if people want to add more classes, the plugin won't recognize them because it's no longer dynamic.
