### ISSUE TITLE
Undefined variable $getBorder

### ISSUE THREAD

**Issue by teguhpermadi** [CodeWithDennis/filament-simple-alert#24]
I want to ask for help. even though I have followed the steps according to the guide

![image](https://github.com/user-attachments/assets/b6537c33-1674-4924-8b3d-f9860e55a692)
![image](https://github.com/user-attachments/assets/58776cf0-7b73-4700-85cf-f14d34489717)
![image](https://github.com/user-attachments/assets/22cb701a-ef3f-442a-a0a5-a6e8dbade394)

**Comment by CodeWithDennis** [comment]
@dissto

**Comment by CodeWithDennis** [comment]
Thank you @dissto !

**Comment by teguhpermadi** [comment]
thanks @dissto
