### ISSUE TITLE
Version 3.0.11 has broken the icon styling

### ISSUE THREAD

**Issue by danr1979** [CodeWithDennis/filament-simple-alert#29]
Hi.

I have recently updated to version 3.0.11 and noticed that the alert text was flush up against the icon instead of there being some space (see attached screenshot).

The previous version (3.0.10) works fine.

![image](https://github.com/user-attachments/assets/73f27355-624d-46a7-bd97-fdeac6beea03)

Dan

**Comment by CodeWithDennis** [comment]
You closed this ticket, did you resolve it? @danr1979

**Comment by danr1979** [comment]
I did. It seems to be working now so might've been something to do with my
environment.

Thanks.

**Comment by Bouhnosaure** [comment]
Hi ! 

I have the same issue on fresh install following the instructions.

It seems the tag `<div class="flex">` on line 30 of the file `resources/views/components/simple-alert.blade.php` misses a `gap-x-3`.

I've tested it on Chrome and Firefox and get the same behavior.

![Image](https://github.com/user-attachments/assets/ab866c1c-3859-4086-8877-c2f199020927)

With the `gap-x-3`

![Image](https://github.com/user-attachments/assets/932c083a-8db2-4ef0-a3de-5c608ef9326e)

Thanks, 

Alex

**Comment by CodeWithDennis** [comment]
Can you check in latest version? Make sure you build your styles and have custom theme setup. @Bouhnosaure

**Comment by Bouhnosaure** [comment]
Indeed, this is due to the not created custom theme.
Thanks !
