### ISSUE TITLE
Infolist

### ISSUE THREAD

**Issue by FortuneV13** [CodeWithDennis/filament-simple-alert#31]
Hi, I saw this package on your twitter and have a good use case for it. Installed and followed the readme from here. 

I get this error: 
`Undefined variable $getIconVerticalAlignment`

Using ` SimpleAlert::make('example')
                    ->columnSpanFull()
                    ->success()
                    ->title('Simple Alert')
                    ->description('This is an example of a simple alert.')
                    `
                    
This is on an infolist within a ViewRecord page on Filament Panels
`use CodeWithDennis\SimpleAlert\Components\Infolists\SimpleAlert;`

**Comment by CodeWithDennis** [comment]
@dissto

**Comment by CodeWithDennis** [comment]
> Hi, I saw this package on your twitter and have a good use case for it. Installed and followed the readme from here. 
> 
> 
> 
> I get this error: 
> 
> `Undefined variable $getIconVerticalAlignment`
> 
> 
> 
> Using ` SimpleAlert::make('example')
> 
>                     ->columnSpanFull()
> 
>                     ->success()
> 
>                     ->title('Simple Alert')
> 
>                     ->description('This is an example of a simple alert.')
> 
>                     `
> 
>                     
> 
> This is on an infolist within a ViewRecord page on Filament Panels
> 
> `use CodeWithDennis\SimpleAlert\Components\Infolists\SimpleAlert;`

Ty for reporting, you could use the previous version while we take a look.

**Comment by CodeWithDennis** [comment]
Can you confirm that it has been resolved in the new version? https://github.com/CodeWithDennis/filament-simple-alert/releases/tag/v3.0.13

@FortuneV13

**Comment by CodeWithDennis** [comment]
> > Can you confirm that it has been resolved in the new version? https://github.com/CodeWithDennis/filament-simple-alert/releases/tag/v3.0.13
> 
> > 
> 
> > @FortuneV13
> 
> 
> 
> Perfect, all working. Thank you. 

Great! Sorry about the inconvenience.
