### ISSUE TITLE
Some styles don't seem to be applying

### ISSUE THREAD

**Issue by thursdaydan** [CodeWithDennis/filament-simple-alert#7]
Hi there! I added this plugin to my project recently and whilst the bulk of it works fantastic, I have noticed some minor but import styles don't seem to be applying with tailwind. 

I've spent all day going over this making sure it's nothing caused by me such as a bad config etc (It still may well be an issue on my end).

Anyway here is an image of how it renders on my local env.
![Screenshot 2024-08-27 at 14 45 55](https://github.com/user-attachments/assets/c80aaec9-23f2-46c0-962f-8a9e57884ce3)

It appears margin and colours are the main styles not being applied for some reason.

Usage inside an infolist:
```php
    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                SimpleAlert::make('success')
                    ->success()
                    ->title(new HtmlString('<strong>Hoorraayy! Your request has been approved! 🎉</strong>'))
                    ->description('Lorem ipsum dolor sit amet consectetur adipisicing elit.')
                    ->link('https://filamentphp.com')
                    ->linkLabel('Read more!')
                    ->linkBlank(true)->columnSpanFull(),
            ]);
    }
```

And here is my tailwind.config.js
```js
import preset from './vendor/filament/support/tailwind.config.preset'
 
export default {
    presets: [preset],
    content: [
        './app/Filament/**/*.php',
        './resources/views/filament/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './vendor/codewithdennis/filament-simple-alert/resources/**/*.blade.php',
    ],
}
```

Any help would be appreciated! Even it is just telling me I've made a schoolboy error somewhere! 

Thanks for the package!

**Comment by CodeWithDennis** [comment]
Make sure you run `npm run build` @thursdaydan

**Comment by CodeWithDennis** [comment]
Thats odd, can you try on a new project and see if it persists?

**Comment by Verringer** [comment]
Can't comment on new projects, but I had this with a pre-existing app with a tailwind config set up before adding filament in.

Adding `->viteTheme('resources/css/app.css')` to the panel service provider solved it for me. Tailwind classes were being built into the app.css but not linked to in the panel.

**Comment by thursdaydan** [comment]
Aye, that's cleared it up nicely. Good catch! Appreciate the help. 👍

**Comment by CodeWithDennis** [comment]
Thanks for the assist. @Verringer

**Comment by thursdaydan** [comment]
I'm happy to close this issue now as this is the solution. I suppose it'd be worth adding a mention in docs for others who may be installing the plugin into an existing project with tailwind already setup.
