### ISSUE TITLE
Alert on form submits a field with the name of the alert

### ISSUE THREAD

**Issue by gthedev** [CodeWithDennis/filament-simple-alert#9]
I have a simple alert on in a Form:
```
                        SimpleAlert::make('balance_alert')
                            ->warning()
                            ->description(function (Get $get) {
                                return sprintf('The account is £%s <b>in credit</b>', $get('balance'));
                            })
                            ->visible(fn (Get $get) => $get('balance') > 0),
```

But when I submit the form, it errors out because it tries to save `balance_alert = null` into the database. Is this intended?

Right now the fix is to `unset` it in the `mutateFormDataBeforeSave` method, is that normal & expected?

Thanks!

**Comment by CodeWithDennis** [comment]
Thanks for reporting i will take a look!

**Comment by CodeWithDennis** [comment]
@gthedev For now you can use `->dehydrated(false)` i will make sure that will be added to the fields in the next update.

**Comment by gthedev** [comment]
@CodeWithDennis great, thanks for your speedy response and help! 🙌

**Comment by CodeWithDennis** [comment]
@gthedev Can you try if its resolved in latest version?

**Comment by gthedev** [comment]
@CodeWithDennis seems to be working well for me, thanks 👌

**Comment by aliaswpeu** [comment]
Hi, usefull plugin, TY!
But I have the same problem. It doesn't matter whether I use dehydrated or not—the data on form submission has grafikAlert = null, which causes a database error stating that the grafikAlert column does not exist. I'm currently unsetting grafikAlert, but that feels like a hacky workaround, and it must be done every time when using SimpleAlert on forms.  Newest version 3.0.17 of SimpleAlert, laravel 11.43.3,  filament 3.2.136.

```
SimpleAlert::make('grafikAlert')
                        ->visible(fn($record) => empty($record->assignee_id))
                        ->warning()
                        ->title(new HtmlString('<strong>Alert</strong>'))
                        ->description('Alert desc')
                        // ->dehydrated(false)
```

**Comment by CodeWithDennis** [comment]
> Hi, usefull plugin, TY! But I have the same problem. It doesn't matter whether I use dehydrated or not—the data on form submission has grafikAlert = null, which causes a database error stating that the grafikAlert column does not exist. I'm currently unsetting grafikAlert, but that feels like a hacky workaround, and it must be done every time when using SimpleAlert on forms. Newest version 3.0.17 of SimpleAlert, laravel 11.43.3, filament 3.2.136.
> 
> ```
> SimpleAlert::make('grafikAlert')
>                         ->visible(fn($record) => empty($record->assignee_id))
>                         ->warning()
>                         ->title(new HtmlString('<strong>Alert</strong>'))
>                         ->description('Alert desc')
>                         // ->dehydrated(false)
> ```

The `->dehydrated(false)` is a part of the plugin for a while now and should ignore the column.

**Comment by aliaswpeu** [comment]
> > Hi, usefull plugin, TY! But I have the same problem. It doesn't matter whether I use dehydrated or not—the data on form submission has grafikAlert = null, which causes a database error stating that the grafikAlert column does not exist. I'm currently unsetting grafikAlert, but that feels like a hacky workaround, and it must be done every time when using SimpleAlert on forms. Newest version 3.0.17 of SimpleAlert, laravel 11.43.3, filament 3.2.136.
> > ```
> > SimpleAlert::make('grafikAlert')
> >                         ->visible(fn($record) => empty($record->assignee_id))
> >                         ->warning()
> >                         ->title(new HtmlString('<strong>Alert</strong>'))
> >                         ->description('Alert desc')
> >                         // ->dehydrated(false)
> > ```
> 
> The `->dehydrated(false)` is a part of the plugin for a while now and should ignore the column.

It's on custom component btw. But on the same component I'v got another dehydrated field and it works fine. I hope this could be helpful :)
